"""Single source of truth for the Código de Poder 777 digital vault catalog.

Generated from the Whop product + pricing export on migration day. Each slug
is Stripe- and download-link-facing — renaming one breaks live checkout links
and any in-flight session, so treat slugs as permanent once this goes live.

`file` is the filename expected under static/vault/<file> once the PDFs are
uploaded. price_cents == 0 marks free lead magnets, which skip Stripe entirely
and deliver immediately on email capture.
"""

MT360_VAULT_PRODUCTS = {
    "guia-de-prompts-de-ia-para-fotografia-de-producto": {
        "name": "Guía de Prompts de IA para Fotografía de Producto",
        "headline": "Fotos de producto con IA que se ven profesionales, no artificiales",
        "price_cents": 1900,
        "lang": "ES",
        "file": "guia-de-prompts-de-ia-para-fotografia-de-producto.pdf",
        "whop_id": "prod_TZL1PoZ5z8zFG",
    },
    "wellness-meal-planner": {
        "name": "Wellness & Meal Planner",
        "headline": "Fuel and Energy for the Woman Running Everything",
        "price_cents": 1900,
        "lang": "EN",
        "file": "wellness-meal-planner.pdf",
        "whop_id": "prod_LQXOuUVb3bOKa",
    },
    "vendor-contractor-management-tracker": {
        "name": "Vendor & Contractor Management Tracker",
        "headline": "Know Who You Pay, and Why, Across Every Brand",
        "price_cents": 1900,
        "lang": "EN",
        "file": "vendor-contractor-management-tracker.pdf",
        "whop_id": "prod_3Xp9UAP0wiftl",
    },
    "testimonial-case-study-builder": {
        "name": "Testimonial & Case Study Builder",
        "headline": "Turn Client Wins Into Marketing You Can Reuse",
        "price_cents": 1900,
        "lang": "EN",
        "file": "testimonial-case-study-builder.pdf",
        "whop_id": "prod_clSczaOTBVpcd",
    },
    "business-startup-workbook": {
        "name": "Business Startup Workbook",
        "headline": "From Idea to First Customer in 90 Days",
        "price_cents": 2700,
        "lang": "EN",
        "file": "business-startup-workbook.pdf",
        "whop_id": "prod_YNoaidovvh579",
    },
    "speaking-media-visibility-tracker": {
        "name": "Speaking & Media Visibility Tracker",
        "headline": "Pitch, Prepare, and Repurpose Every Appearance",
        "price_cents": 2200,
        "lang": "EN",
        "file": "speaking-media-visibility-tracker.pdf",
        "whop_id": "prod_G2sYu5SuWCGpW",
    },
    "shadow-work-mindfulness-journal": {
        "name": "Shadow Work & Mindfulness Journal",
        "headline": "The Inner Work Underneath the Business Work",
        "price_cents": 2200,
        "lang": "EN",
        "file": "shadow-work-mindfulness-journal.pdf",
        "whop_id": "prod_Ol4m3N1mpvAT7",
    },
    "seasonal-holiday-promotion-planner": {
        "name": "Seasonal & Holiday Promotion Planner",
        "headline": "Plan Every Sale Season Ahead of Time",
        "price_cents": 2200,
        "lang": "EN",
        "file": "seasonal-holiday-promotion-planner.pdf",
        "whop_id": "prod_EfzyAaShzi6m1",
    },
    "business-retreat-travel-planner": {
        "name": "Business Retreat & Travel Planner",
        "headline": "Step Away Without Everything Falling Apart",
        "price_cents": 1900,
        "lang": "EN",
        "file": "business-retreat-travel-planner.pdf",
        "whop_id": "prod_Y8SqNjH6tQZnU",
    },
    "referral-word-of-mouth-growth-tracker": {
        "name": "Referral & Word-of-Mouth Growth Tracker",
        "headline": "Turn Happy Customers Into Your Best Marketing Channel",
        "price_cents": 1900,
        "lang": "EN",
        "file": "referral-word-of-mouth-growth-tracker.pdf",
        "whop_id": "prod_gGGlqZTUslkVD",
    },
    "reading-personal-growth-journal": {
        "name": "Reading & Personal Growth Journal",
        "headline": "Turn What You Learn Into What You Actually Do",
        "price_cents": 1900,
        "lang": "EN",
        "file": "reading-personal-growth-journal.pdf",
        "whop_id": "prod_9fWYi7lhpi7NZ",
    },
    "podcast-video-content-planner": {
        "name": "Podcast & Video Content Planner",
        "headline": "Plan, Record, and Repurpose Every Episode",
        "price_cents": 2200,
        "lang": "EN",
        "file": "podcast-video-content-planner.pdf",
        "whop_id": "prod_iSpxHZQyWwYe3",
    },
    "personal-branding-workbook": {
        "name": "Personal Branding Workbook",
        "headline": "The Throughline Across Every Business You Run",
        "price_cents": 2400,
        "lang": "EN",
        "file": "personal-branding-workbook.pdf",
        "whop_id": "prod_zVjBUrHbVqHII",
    },
    "customer-onboarding-fulfillment-kit": {
        "name": "Customer Onboarding & Fulfillment Kit",
        "headline": "Give Every Client a White-Glove Experience, On Repeat",
        "price_cents": 2400,
        "lang": "EN",
        "file": "customer-onboarding-fulfillment-kit.pdf",
        "whop_id": "prod_DsmJY94GQWjEZ",
    },
    "email-newsletter-list-growth-planner": {
        "name": "Email Newsletter & List Growth Planner",
        "headline": "Write Consistently, Grow On Purpose",
        "price_cents": 1900,
        "lang": "EN",
        "file": "email-newsletter-list-growth-planner.pdf",
        "whop_id": "prod_VVQOFziWNWrDM",
    },
    "networking-relationship-building-tracker": {
        "name": "Networking & Relationship Building Tracker",
        "headline": "Maintain the Network, Not Just Mine It",
        "price_cents": 1700,
        "lang": "EN",
        "file": "networking-relationship-building-tracker.pdf",
        "whop_id": "prod_WES5XCwIAozBT",
    },
    "meeting-decision-log": {
        "name": "Meeting & Decision Log",
        "headline": "Never Lose Track of What Was Decided, or By Whom",
        "price_cents": 1900,
        "lang": "EN",
        "file": "meeting-decision-log.pdf",
        "whop_id": "prod_VABNBqTjdXyL9",
    },
    "marketing-launch-campaign-planner": {
        "name": "Marketing & Launch Campaign Planner",
        "headline": "Plan Every Launch Like a System, Not a Scramble",
        "price_cents": 2400,
        "lang": "EN",
        "file": "marketing-launch-campaign-planner.pdf",
        "whop_id": "prod_ZdvKlJ6M9SUoW",
    },
    "investment-wealth-building-tracker": {
        "name": "Investment & Wealth Building Tracker",
        "headline": "See the Whole Picture Across Every Asset",
        "price_cents": 2200,
        "lang": "EN",
        "file": "investment-wealth-building-tracker.pdf",
        "whop_id": "prod_GCfk5pvONjEtT",
    },
    "home-household-management-planner": {
        "name": "Home & Household Management Planner",
        "headline": "Run Your Home Like the System It Actually Is",
        "price_cents": 1900,
        "lang": "EN",
        "file": "home-household-management-planner.pdf",
        "whop_id": "prod_c4Xn6SZio2mrP",
    },
    "gratitude-affirmation-journal": {
        "name": "Gratitude & Affirmation Journal",
        "headline": "30 Days of Rewiring How You Talk to Yourself",
        "price_cents": 1900,
        "lang": "EN",
        "file": "gratitude-affirmation-journal.pdf",
        "whop_id": "prod_F7Vqy7fEtLMr7",
    },
    "deep-work-time-blocking-planner": {
        "name": "Deep Work & Time Blocking Planner",
        "headline": "Protect the Hours That Actually Move the Needle",
        "price_cents": 2200,
        "lang": "EN",
        "file": "deep-work-time-blocking-planner.pdf",
        "whop_id": "prod_G846Zwy9j2wJI",
    },
    "debt-payoff-savings-challenge-tracker": {
        "name": "Debt Payoff & Savings Challenge Tracker",
        "headline": "Pay It Down, Save It Up, On Your Terms",
        "price_cents": 1700,
        "lang": "EN",
        "file": "debt-payoff-savings-challenge-tracker.pdf",
        "whop_id": "prod_qIpx9cxVUH8LC",
    },
    "course-creator-workbook": {
        "name": "Course Creator Workbook",
        "headline": "From Expertise to a Finished, Sellable Course",
        "price_cents": 2700,
        "lang": "EN",
        "file": "course-creator-workbook.pdf",
        "whop_id": "prod_gQobZFuGecVaX",
    },
    "burnout-prevention-recovery-workbook": {
        "name": "Burnout Prevention & Recovery Workbook",
        "headline": "Catch It Early, Recover Fully, Build Sustainably",
        "price_cents": 2200,
        "lang": "EN",
        "file": "burnout-prevention-recovery-workbook.pdf",
        "whop_id": "prod_2k1pLMf0M9ruM",
    },
    "year-in-review-annual-planning-workbook": {
        "name": "Year in Review & Annual Planning Workbook",
        "headline": "Close One Chapter Well, Open the Next On Purpose",
        "price_cents": 2400,
        "lang": "EN",
        "file": "year-in-review-annual-planning-workbook.pdf",
        "whop_id": "prod_euJ8rowkrwmU5",
    },
    "adhd-friendly-focus-productivity-planner": {
        "name": "ADHD-Friendly Focus & Productivity Planner",
        "headline": "Built for Brains That Don't Work in Straight Lines",
        "price_cents": 2200,
        "lang": "EN",
        "file": "adhd-friendly-focus-productivity-planner.pdf",
        "whop_id": "prod_WvNcDlC5qPyys",
    },
    "companion-workbook-multitask360-es": {
        "name": "Companion Workbook MultiTask360 (ES)",
        "headline": "El Método Detrás de Todo el Vault",
        "price_cents": 2900,
        "lang": "ES",
        "file": "companion-workbook-multitask360-es.pdf",
        "whop_id": "prod_2Xc5SnNP1Ti0s",
    },
    "diario-de-reinicio-semanal": {
        "name": "Diario de Reinicio Semanal",
        "headline": "Un Ritual de Cinco Minutos para Cerrar Bien Cada Semana",
        "price_cents": 1700,
        "lang": "EN",
        "file": "diario-de-reinicio-semanal.pdf",
        "whop_id": "prod_3RPznnYN66Thx",
    },
    "planificador-diario-90-dias-sin-fecha": {
        "name": "Planificador Diario (90 Días Sin Fecha)",
        "headline": "Empieza Cuando Quieras",
        "price_cents": 2400,
        "lang": "ES",
        "file": "planificador-diario-90-dias-sin-fecha.pdf",
        "whop_id": "prod_Iavp9jueeW3DO",
    },
    "rastreador-de-presupuesto-e-ingresos": {
        "name": "Rastreador de Presupuesto e Ingresos",
        "headline": "Ve los Números de Cada Marca, Claramente",
        "price_cents": 1900,
        "lang": "EN",
        "file": "rastreador-de-presupuesto-e-ingresos.pdf",
        "whop_id": "prod_VR8wHKGBsrNut",
    },
    "rastreador-de-clientes-y-crm": {
        "name": "Rastreador de Clientes y CRM",
        "headline": "Nunca Más Pierdas un Seguimiento",
        "price_cents": 1900,
        "lang": "EN",
        "file": "rastreador-de-clientes-y-crm.pdf",
        "whop_id": "prod_oPJpsAX3Izlkp",
    },
    "dashboard-ceo-y-kpi": {
        "name": "Dashboard CEO y KPI",
        "headline": "Los Números Detrás de Cada Marca, en Un Solo Lugar",
        "price_cents": 2700,
        "lang": "EN",
        "file": "dashboard-ceo-y-kpi.pdf",
        "whop_id": "prod_iwJrKyp2VMvfi",
    },
    "rastreador-de-habitos-y-tiempo": {
        "name": "Rastreador de Hábitos y Tiempo",
        "headline": "Descubre En Qué Se Va Realmente Tu Día",
        "price_cents": 1700,
        "lang": "ES",
        "file": "rastreador-de-habitos-y-tiempo.pdf",
        "whop_id": "prod_vfEeyueYOaks4",
    },
    "workbook-de-procesos-y-automatizacion": {
        "name": "Workbook de Procesos y Automatización",
        "headline": "Convierte Lo Que Tienes en la Cabeza en Algo Delegable",
        "price_cents": 2700,
        "lang": "ES",
        "file": "workbook-de-procesos-y-automatizacion.pdf",
        "whop_id": "prod_poBoasBPY4axR",
    },
    "biblioteca-de-prompts-de-ia": {
        "name": "Biblioteca de Prompts de IA",
        "headline": "216 Prompts para la Emprendedora Multi-Marca",
        "price_cents": 1900,
        "lang": "EN",
        "file": "biblioteca-de-prompts-de-ia.pdf",
        "whop_id": "prod_XmffH5HW2I0Cd",
    },
    "planificador-de-contenido-y-redes-sociales": {
        "name": "Planificador de Contenido y Redes Sociales",
        "headline": "Planifica, Agrupa y Reutiliza Sin Agotarte",
        "price_cents": 2900,
        "lang": "EN",
        "file": "planificador-de-contenido-y-redes-sociales.pdf",
        "whop_id": "prod_tHKZzn9xSdU4y",
    },
    "diario-de-metas-y-vision": {
        "name": "Diario de Metas y Visión",
        "headline": "El Trabajo Interior Detrás de Tu Plan de 90 Días",
        "price_cents": 2700,
        "lang": "ES",
        "file": "diario-de-metas-y-vision.pdf",
        "whop_id": "prod_2hMXakS1SjzEa",
    },
    "blueprint-de-negocios-con-ia-el-planificador-de-90-dias": {
        "name": "Blueprint de Negocios con IA: El Planificador de 90 Días",
        "headline": "Metas, Contenido, Flujos de IA y Finanzas en Un Solo Sistema",
        "price_cents": 4700,
        "lang": "ES",
        "file": "blueprint-de-negocios-con-ia-el-planificador-de-90-dias.pdf",
        "whop_id": "prod_Xh9P9c4LOAqAr",
    },
    "ai-productivity-vault-full-bundle-spanish": {
        "name": "AI Productivity Vault — Full Bundle (Spanish)",
        "headline": "Los 12 Productos en Español — La Colección Completa",
        "price_cents": 9700,
        "lang": "ES",
        "file": "ai-productivity-vault-full-bundle-spanish.pdf",
        "whop_id": "prod_iDaDuuL9A9WcT",
    },
    "ai-productivity-vault-full-bundle-english": {
        "name": "AI Productivity Vault — Full Bundle (English)",
        "headline": "All 38 English Products — The Entire Vault in One Download",
        "price_cents": 9700,
        "lang": "EN",
        "file": "ai-productivity-vault-full-bundle-english.pdf",
        "whop_id": "prod_pzOzGvjaV3bz6",
    },
    "multitask360-companion-workbook": {
        "name": "MultiTask360 Companion Workbook",
        "headline": "The method behind the whole vault.",
        "price_cents": 2900,
        "lang": "EN",
        "file": "multitask360-companion-workbook.pdf",
        "whop_id": "prod_7N3pKTXKyr3R0",
    },
    "weekly-reset-reflection-journal": {
        "name": "Weekly Reset & Reflection Journal",
        "headline": "A five-minute ritual to close every week well.",
        "price_cents": 1700,
        "lang": "EN",
        "file": "weekly-reset-reflection-journal.pdf",
        "whop_id": "prod_G5DWvHa0Pj5yd",
    },
    "daily-planner-90-undated-days": {
        "name": "Daily Planner — 90 Undated Days",
        "headline": "Start any time. No wasted pages.",
        "price_cents": 2400,
        "lang": "EN",
        "file": "daily-planner-90-undated-days.pdf",
        "whop_id": "prod_5ii2w9ySko5NI",
    },
    "budget-income-tracker": {
        "name": "Budget & Income Tracker",
        "headline": "See every brand's numbers, clearly.",
        "price_cents": 1900,
        "lang": "EN",
        "file": "budget-income-tracker.pdf",
        "whop_id": "prod_j9JsGgq5vYiQt",
    },
    "client-crm-tracker": {
        "name": "Client & CRM Tracker",
        "headline": "Never lose track of a follow-up again.",
        "price_cents": 1900,
        "lang": "EN",
        "file": "client-crm-tracker.pdf",
        "whop_id": "prod_C7tGUHKjJXJi9",
    },
    "ceo-dashboard-kpi-tracker": {
        "name": "CEO Dashboard & KPI Tracker",
        "headline": "The numbers behind every brand, in one place.",
        "price_cents": 2700,
        "lang": "EN",
        "file": "ceo-dashboard-kpi-tracker.pdf",
        "whop_id": "prod_bsZGwQIayqrje",
    },
    "habit-time-tracker": {
        "name": "Habit & Time Tracker",
        "headline": "See where your days actually go.",
        "price_cents": 1700,
        "lang": "EN",
        "file": "habit-time-tracker.pdf",
        "whop_id": "prod_gOep44t3z1A2v",
    },
    "sop-automation-workbook": {
        "name": "SOP & Automation Workbook",
        "headline": "Turn what's in your head into something you can hand off.",
        "price_cents": 2700,
        "lang": "EN",
        "file": "sop-automation-workbook.pdf",
        "whop_id": "prod_gvTrpuroRiUEH",
    },
    "ai-prompt-library-216-prompts-for-the-multi-brand-entrepreneur-e9": {
        "name": "AI Prompt Library — 216 Prompts for the Multi-Brand Entrepreneur",
        "headline": "Stop staring at a blank AI chat. Copy, paste, customize, done.",
        "price_cents": 1900,
        "lang": "EN",
        "file": "ai-prompt-library-216-prompts-for-the-multi-brand-entrepreneur-e9.pdf",
        "whop_id": "prod_rLH4VTejWTq6Z",
    },
    "content-social-media-planner-9a": {
        "name": "Content & Social Media Planner",
        "headline": "Stop starting from a blank page. Build your pillars once, pull from them all qua",
        "price_cents": 2900,
        "lang": "EN",
        "file": "content-social-media-planner-9a.pdf",
        "whop_id": "prod_Ao5hQllATuldk",
    },
    "goal-vision-companion-journal": {
        "name": "Goal & Vision Companion Journal",
        "headline": "Get honest about what you actually want before you plan another goal you don't f",
        "price_cents": 2700,
        "lang": "EN",
        "file": "goal-vision-companion-journal.pdf",
        "whop_id": "prod_Wxu3JmtCJsTJd",
    },
    "ai-business-blueprint-the-90-day-planner-for-multi-passionate-entrepreneurs": {
        "name": "AI Business Blueprint: The 90-Day Planner for Multi-Passionate Entrepreneurs",
        "headline": "Plan your goals, content, AI workflows, and cash flow — in one system built for ",
        "price_cents": 4700,
        "lang": "EN",
        "file": "ai-business-blueprint-the-90-day-planner-for-multi-passionate-entrepreneurs.pdf",
        "whop_id": "prod_MQDDF2eT3efBP",
    },
    "10-ai-prompts-to-start-your-business": {
        "name": "10 AI Prompts to Start Your Business",
        "headline": "Free AI prompts to help you kickstart your own business",
        "price_cents": 0,
        "lang": "EN",
        "file": "10-ai-prompts-to-start-your-business.pdf",
        "whop_id": "prod_YYwYOUoOEyZgb",
    },
    "blu-royal-academy-full-program-implementation": {
        "name": "Blu Royal Academy — Full Program Implementation",
        "headline": "The complete bilingual curriculum library — every file we offer, including all S",
        "price_cents": 249900,
        "lang": "EN",
        "file": "blu-royal-academy-full-program-implementation.pdf",
        "whop_id": "prod_mr0p8kslw2rZu",
    },
    "blu-royal-academy-intermediate-growth-kit": {
        "name": "Blu Royal Academy — Intermediate Growth Kit",
        "headline": "Expanded download package for a deeper curriculum library and more printable res",
        "price_cents": 150000,
        "lang": "EN",
        "file": "blu-royal-academy-intermediate-growth-kit.pdf",
        "whop_id": "prod_41o8JwKiEmZ3J",
    },
    "blu-royal-academy-basic-curriculum-kit": {
        "name": "Blu Royal Academy — Basic Curriculum Kit",
        "headline": "Starter download bundle for teachers & homeschool parents who need preschool pla",
        "price_cents": 49700,
        "lang": "EN",
        "file": "blu-royal-academy-basic-curriculum-kit.pdf",
        "whop_id": "prod_qyueSRHmXtBsW",
    },
    "blu-royal-academy-fine-motor-skills-mega-pack": {
        "name": "Blu Royal Academy — Fine Motor Skills Mega Pack",
        "headline": "Quick-start printable pack for grip, tracing, cutting & hand coordination",
        "price_cents": 1700,
        "lang": "EN",
        "file": "blu-royal-academy-fine-motor-skills-mega-pack.pdf",
        "whop_id": "prod_L78qfA7PHJAiJ",
    },
    "dj-event-assistant-ai-professional-yearly": {
        "name": "DJ Event Assistant AI — Professional (Yearly)",
        "headline": "Best value for established DJs managing frequent events",
        "price_cents": 24999,
        "lang": "EN",
        "file": "dj-event-assistant-ai-professional-yearly.pdf",
        "whop_id": "prod_A9VOfNQ77UrmG",
    },
    "dj-event-assistant-ai-professional-monthly": {
        "name": "DJ Event Assistant AI — Professional (Monthly)",
        "headline": "Scale premium events with AI planning and financial visibility",
        "price_cents": 3000,
        "lang": "EN",
        "file": "dj-event-assistant-ai-professional-monthly.pdf",
        "whop_id": "prod_kYckWJsrWbS7j",
    },
    "dj-event-assistant-ai-starter-yearly": {
        "name": "DJ Event Assistant AI — Starter (Yearly)",
        "headline": "Save annually while running your full starter workflow",
        "price_cents": 14900,
        "lang": "EN",
        "file": "dj-event-assistant-ai-starter-yearly.pdf",
        "whop_id": "prod_SkclUxgwiOAXE",
    },
    "dj-event-assistant-ai-starter-monthly": {
        "name": "DJ Event Assistant AI — Starter (Monthly)",
        "headline": "Run bookings, clients & invoices with one AI command center",
        "price_cents": 1500,
        "lang": "EN",
        "file": "dj-event-assistant-ai-starter-monthly.pdf",
        "whop_id": "prod_Ig0XXD12kl6A1",
    },
    "digital-gap-year-starter-guide": {
        "name": "Digital Gap Year Starter Guide",
        "headline": "Digital Gap Year Starter Guide — How to Travel and Work from Anywhere",
        "price_cents": 1700,
        "lang": "EN",
        "file": "digital-gap-year-starter-guide.pdf",
        "whop_id": "prod_qYV9bUsWT2tp0",
    },
    "lower-cholesterol-naturally": {
        "name": "Lower Cholesterol Naturally",
        "headline": "Lower Cholesterol Naturally — The Complete Practical Guide",
        "price_cents": 1200,
        "lang": "EN",
        "file": "lower-cholesterol-naturally.pdf",
        "whop_id": "prod_Tz2uTzsntsY7c",
    },
    "deja-de-comprar-por-impulso": {
        "name": "Deja de Comprar por Impulso",
        "headline": "Controla tu gasto en 21 días con un sistema simple de compra consciente · Ebook ",
        "price_cents": 1700,
        "lang": "EN",
        "file": "deja-de-comprar-por-impulso.pdf",
        "whop_id": "prod_oHkD6UlwZk9Mk",
    },
    "limites-sanos-di-que-no-sin-culpa": {
        "name": "Límites Sanos: Di que No sin Culpa",
        "headline": "Aprende a decir que no sin culpa en 21 días · Ebook en Español",
        "price_cents": 1700,
        "lang": "ES",
        "file": "limites-sanos-di-que-no-sin-culpa.pdf",
        "whop_id": "prod_Oj9GdBIt3oSsq",
    },
    "plan-luxury-workbook-multitasking360-vip": {
        "name": "Plan Luxury — Workbook multitasking360 (VIP)",
        "headline": "La experiencia VIP: done-for-you, mentoría extendida y bóveda de recursos · Espa",
        "price_cents": 14900,
        "lang": "EN",
        "file": "plan-luxury-workbook-multitasking360-vip.pdf",
        "whop_id": "prod_hfE3jSsvSoMMm",
    },
    "plan-premium-workbook-multitasking360-1-1": {
        "name": "Plan Premium — Workbook multitasking360 (1:1)",
        "headline": "Acompañamiento 1:1 + workbook · Estrategia personalizada · Español & English",
        "price_cents": 7900,
        "lang": "ES",
        "file": "plan-premium-workbook-multitasking360-1-1.pdf",
        "whop_id": "prod_r5D7maboOVKJq",
    },
    "plan-pro-workbook-multitasking360": {
        "name": "Plan Pro — Workbook multitasking360",
        "headline": "Escala tu marca, contenido y ventas · Español & English",
        "price_cents": 4900,
        "lang": "ES",
        "file": "plan-pro-workbook-multitasking360.pdf",
        "whop_id": "prod_AqC6tjB86N1pN",
    },
    "plan-basico-workbook-multitasking360": {
        "name": "Plan Básico — Workbook multitasking360",
        "headline": "Construye las bases de tu negocio online · Español & English",
        "price_cents": 2900,
        "lang": "ES",
        "file": "plan-basico-workbook-multitasking360.pdf",
        "whop_id": "prod_I9lbn8qQGWRVb",
    },
    "multitask360-pro-membership": {
        "name": "🏆 MultiTask360 Pro Membership",
        "headline": "Premium AI apps, business systems, templates & exclusive member resources.",
        "price_cents": 2999,
        "lang": "EN",
        "file": "multitask360-pro-membership.pdf",
        "whop_id": "prod_RxJCcPaKb819p",
    },
    "the-hook-rules-5-rules-for-unskippable-hooks": {
        "name": "The Hook Rules: 5 Rules for Unskippable Hooks",
        "headline": "Write first lines that stop the scroll, grab attention, and get your content rea",
        "price_cents": 1700,
        "lang": "EN",
        "file": "the-hook-rules-5-rules-for-unskippable-hooks.pdf",
        "whop_id": "prod_UCQ1rM3Q568yb",
    },
    "5-prompts-to-start-a-youtube-channel": {
        "name": "5 Prompts to Start a YouTube Channel",
        "headline": "Launch a Profitable Youtube Channel with 5 AI Prompts",
        "price_cents": 1700,
        "lang": "EN",
        "file": "5-prompts-to-start-a-youtube-channel.pdf",
        "whop_id": "prod_g0XAnpxXQLy2d",
    },
    "12-gemini-prompts-that-save-hours-every-week": {
        "name": "12 Gemini Prompts That Save Hours Every Week",
        "headline": "Copy Paste and turn Gmail Docs & Drive into your AI assistant.",
        "price_cents": 700,
        "lang": "EN",
        "file": "12-gemini-prompts-that-save-hours-every-week.pdf",
        "whop_id": "prod_UmiGcwS1RxbLI",
    },
    "complete-ai-video-editing-stack-2026-edition": {
        "name": "COMPLETE AI VIDEO EDITING STACK 2026 100+ AI Tools, Prompts & Workflows",
        "headline": "Learn how to script, generate, edit, enhance, and publish professional AI videos",
        "price_cents": 700,
        "lang": "EN",
        "file": "complete-ai-video-editing-stack-2026-edition.pdf",
        "whop_id": "prod_XHXWdJxVfIJYj",
    },
    "hidden-income-finder": {
        "name": "Hidden Income Finder",
        "headline": "Discover the Business Opportunity Hidden in Your Experience",
        "price_cents": 0,
        "lang": "EN",
        "file": "hidden-income-finder.pdf",
        "whop_id": "prod_bXVhKyk3ITESu",
    },
}
